# Generated by Django 5.0 on 2024-09-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Pagamento')),
                ('type_moviment', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SAIDA', 'SAIDA')], max_length=255, verbose_name='Tipo de Movimentação')),
                ('reference_at', models.CharField(choices=[('MENSALIDADE', 'MENSALIDADE'), ('TAXA ARBITRAGEM', 'TAXA ARBITRAGEM'), ('ALUGUEL BAR', 'ALUGUEL BAR'), ('OUTROS', 'OUTROS')], max_length=255, verbose_name='Referente a')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do pagamento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['dt_emissao'],
            },
        ),
    ]
