# Generated by Django 5.0 on 2024-09-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_payment', '0002_ticket_name_payment_ticket_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-dt_emissao'], 'verbose_name': 'Mensalidade', 'verbose_name_plural': 'Mensalidades'},
        ),
    ]
