# Generated by Django 5.0 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_payment', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dt_emissao',
            field=models.DateTimeField(verbose_name='Data de Pagamento'),
        ),
    ]
