# Generated by Django 5.0 on 2024-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_payment', '0004_alter_ticket_dt_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reference_at',
            field=models.CharField(choices=[('MENSALIDADE', 'MENSALIDADE'), ('JOIA', 'JOIA'), ('ALUGUEL BAR', 'ALUGUEL BAR'), ('OUTROS', 'OUTROS'), ('TAXA ARBITRAGEM', 'TAXA ARBITRAGEM')], max_length=255, verbose_name='Referente a'),
        ),
    ]
