# Generated by Django 5.0 on 2024-09-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_emissao', models.DateTimeField(auto_now_add=True)),
                ('name_associate', models.CharField(max_length=255, verbose_name='Nome do Associado')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_guest', models.CharField(max_length=255, verbose_name='Nome do Convidado')),
                ('doc_guest', models.CharField(max_length=15, verbose_name='Documento do Convidado')),
                ('invite_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.inviteticket', verbose_name='ID Ticket')),
            ],
        ),
    ]
