# Generated by Django 5.0 on 2024-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['name_guest'], 'verbose_name': 'Convidado'},
        ),
        migrations.AlterModelOptions(
            name='inviteticket',
            options={'ordering': ['dt_emissao'], 'verbose_name': 'Cortesia Retirada', 'verbose_name_plural': 'Cortesias Retiradas'},
        ),
    ]
