# Generated by Django 5.0 on 2024-09-05 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_alter_invite_options_alter_inviteticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteticket',
            name='type_associate',
            field=models.CharField(choices=[('AGREGADO(A)', 'AGREGADO(A)'), ('SINDICALIZADO(A)', 'SINDICALIZADO(A)')], default=datetime.datetime(2024, 9, 5, 14, 58, 14, 272009), max_length=30, verbose_name='Tipo de Sócio'),
            preserve_default=False,
        ),
    ]
