# Generated by Django 5.0 on 2024-09-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_inviteticket_type_associate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteticket',
            options={'ordering': ['dt_emissao'], 'verbose_name': 'Cortesia', 'verbose_name_plural': 'Cortesias'},
        ),
        migrations.AddField(
            model_name='inviteticket',
            name='invite_status',
            field=models.CharField(choices=[('CANCELADO', 'CANCELADO'), ('RETIRADO', 'RETIRADO'), ('SOLICITADO', 'SOLICITADO')], default=datetime.datetime(2024, 9, 6, 10, 48, 16, 332411), max_length=30, verbose_name='Status do Convite'),
            preserve_default=False,
        ),
    ]
