# Generated by Django 5.0 on 2024-09-20 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0006_alter_inviteticket_dt_emissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteticket',
            name='invite_status',
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_status',
            field=models.CharField(choices=[('CANCELADO', 'CANCELADO'), ('RETIRADO', 'RETIRADO'), ('SOLICITADO', 'SOLICITADO')], default=django.utils.timezone.now, max_length=30, verbose_name='Status do Convite'),
            preserve_default=False,
        ),
    ]
