# Generated by Django 5.0 on 2024-09-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_emissao', models.DateTimeField(auto_now_add=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='InviteSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_guest', models.CharField(max_length=255, verbose_name='Nome do Convidado')),
                ('doc_guest', models.CharField(max_length=15, verbose_name='Documento do Convidado')),
                ('payment_method', models.CharField(choices=[('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'), ('DINHEIRO', 'DINHEIRO'), ('PIX', 'PIX')], max_length=30, verbose_name='Forma de Pagamento')),
                ('invite_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite_sale.inviteticket', verbose_name='ID Ticket')),
                ('type_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite_sale.typeinvite', verbose_name='Tipo de Convite')),
            ],
        ),
    ]
