# Generated by Django 5.0 on 2024-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteticket',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
