# Generated by Django 5.0 on 2024-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0002_alter_inviteticket_total_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitesale',
            options={'ordering': ['name_guest'], 'verbose_name': 'Comprador', 'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='inviteticket',
            options={'ordering': ['dt_emissao'], 'verbose_name': 'Convite Vendido', 'verbose_name_plural': 'Convites Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='typeinvite',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Convite', 'verbose_name_plural': 'Tipos de Convites'},
        ),
    ]
