# Generated by Django 5.0 on 2024-09-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0003_alter_invitesale_options_alter_inviteticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteticket',
            options={'ordering': ['-dt_emissao'], 'verbose_name': 'Convite Vendido', 'verbose_name_plural': 'Convites Vendidos'},
        ),
    ]
