# Generated by Django 5.0 on 2024-09-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0004_alter_inviteticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_ative', models.BooleanField(default=False, verbose_name='Rateio')),
                ('description_rateio', models.CharField(max_length=255, verbose_name='Descrição do Rateio')),
                ('invite_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite_sale.inviteticket', verbose_name='ID Ticket')),
            ],
        ),
    ]
