# Generated by Django 5.0 on 2024-09-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0005_rateio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rateio',
        ),
    ]
