# Generated by Django 5.0 on 2024-09-10 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0006_delete_rateio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteticket',
            name='description',
            field=models.CharField(default=datetime.datetime(2024, 9, 10, 14, 32, 16, 467673), max_length=255, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
