# Generated by Django 5.0 on 2024-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0007_inviteticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteticket',
            name='dt_emissao',
            field=models.DateTimeField(),
        ),
    ]
