# Generated by Django 5.0 on 2024-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite_sale', '0008_alter_inviteticket_dt_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteticket',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
